// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Board from "./islands/Board.tsx";
import * as $CardModal from "./islands/CardModal.tsx";
import * as $ChangelogModal from "./islands/ChangelogModal.tsx";
import * as $DarkModeToggle from "./islands/DarkModeToggle.tsx";
import * as $DeleteCardModal from "./islands/DeleteCardModal.tsx";
import * as $HeaderControls from "./islands/HeaderControls.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $Statistics from "./islands/Statistics.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Board.tsx": $Board,
    "./islands/CardModal.tsx": $CardModal,
    "./islands/ChangelogModal.tsx": $ChangelogModal,
    "./islands/DarkModeToggle.tsx": $DarkModeToggle,
    "./islands/DeleteCardModal.tsx": $DeleteCardModal,
    "./islands/HeaderControls.tsx": $HeaderControls,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/Statistics.tsx": $Statistics,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
